car_dealership/urls.py
from django.contrib import admin
from django.urls import include, path

admin.site.site_header = 'Car Dealership'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls')),
]

web/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = 'web'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register, name='register'),
    path('cars/', views.cars_page, name='cars'),
    path('car_dy/', views.cars, name='car_dy'),
    path('car_s/', views.car_search, name='search'),
    path('car/<int:cid>', views.car_details, name='details'),
    path('testdrive/<int:cid>', views.testdrive, name="testdrive"),
    path('ordercar/<int:cid>', views.order_car, name='order'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('post_car/', views.post_car, name="post_car"),
    path('compare/', views.compare, name='compare'),
    path('create_test_drive', views.create_test_drive, name='create_test_drive'),
    path('order_approve', views.order_approve, name='order_approve'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/templates/web/compare.html
{% extends 'web/base_alt.html' %}
{% load static %}
{% load bootstrap4 %}
{% block title %}Compare{% endblock %}
{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/css_style.default.css' %}" id="theme-stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-select.min.css' %}" id="theme-stylesheet">
    <script src="{% static 'js/nouislider.min.js' %}"></script>
{% endblock %}

{% block menu %}
    <ul class="navbar-nav ml-auto">
        <li class="nav-item">
            <form class="form-inline my-2 my-lg-0" id="searchbar">
                <input class="form-control ml-sm-2" type="text" name="search" placeholder="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit" id="submit">Search</button>
            </form>
        </li>
        &nbsp;&nbsp;
        <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'web:cars' %}">Cars</a>
        </li>
        {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="{% url 'web:post_car' %}">Post Car</a>
            </li>
            {% if user.is_staff %}
           <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="{% url 'web:create_test_drive' %}">Drive Panel</a>
        </li>
       <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="/admin/web/order/">Order Panel</a>
        </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="{% url 'web:dashboard' %}">Welcome, {{ user.last_name }}</a>
            </li>
            {% endif %}
            <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="{% url 'web:logout' %}">Logout</a>
            </li>
        {% else %}
            <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="{% url 'web:login' %}">Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="{% url 'web:register' %}">Register</a>
            </li>
        {% endif %}
    </ul>
{% endblock %}

{% block body %}
    <section class="hero hero-page gray-bg padding-small">
        <div class="container">
            <div class="row d-flex">
                <div class="col-lg-9 order-2 order-lg-1">
                    <h1>Compare cars</h1>
                    <p class="lead text-muted">Specs of 2 cars, side by side</p>
                </div>
                <div class="col-lg-3 text-right order-1 order-lg-2">
                    <ul class="breadcrumb justify-content-lg-end">
                        <li class="breadcrumb-item"><a href="{% url 'web:index' %}">Home</a></li>
                        <li class="breadcrumb-item active">compare</li>
                    </ul>
                </div>
            </div>
        </div>
    </section>
    <main>
        <div class="container">
            <div class="row">
                <!-- Select-->
                <div class="products-grid col-xl-12 col-lg-12" style="text-align: center">
                    <form id="compareForm" class="form form-control" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% bootstrap_form form layout='horizontal'%}
                        {% buttons %}
                            <button type="submit" class="btn btn-success" id="compareBtn">Compare</button>
                        {% endbuttons %}
                    </form>
                </div>
            </div>
                <!-- /Select end-->
            <div class="row">
                <!-- Grid -->
                <div class="products-grid col-xl-12 col-lg-12 sidebar-left">
                    <div class="row grid" id="tablezone">
                        <!-- item-->
                    </div>
                </div>
                <!-- / Grid End-->
            </div>
        </div>
    </main>
{% endblock %}
{% block scripts %}
    <script src="{% static 'js/bootstrap-select.min.js' %}" type="text/javascript"></script>
    <script>
        $("#compareForm").submit(function(e) {
            var url = "{% url 'web:compare' %}";
            $.ajax({
                type: "POST",
                url: url,
                data: $("#compareForm").serialize(),
                success: function(data) {
                    $('#cmpTable').remove();
                    $('#tablezone').append(data);
                }
            });
            e.preventDefault();
        });
    </script>
{% endblock %}

web/templates/web/create_test_drive.html
{% extends 'web/base_alt.html' %}
{% load widget_tweaks %}
{% load static %}
{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/css_style.default.css' %}" id="theme-stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-datepicker.min.css' %}" id="theme-stylesheet">
{% endblock %}

{% block menu %}

    <ul class="navbar-nav ml-auto">
        <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'web:cars' %}">Cars</a>
        </li>
        {% if user.is_authenticated %}
            {% if user.is_staff %}
           <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="{% url 'web:create_test_drive' %}">Drive Panel</a>
        </li>
       <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="/admin/web/order/">Order Panel</a>
        </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="{% url 'web:dashboard' %}">Welcome, {{ user.last_name }}</a>
            </li>
            {% endif %}
            <li class="nav-item">
                <a class="nav-link js-scroll-t rigger" href="{% url 'web:logout' %}">Logout</a>
            </li>
        {% else %}
            <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="{% url 'web:login' %}">Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="{% url 'web:register' %}">Register</a>
            </li>
        {% endif %}
    </ul>
{% endblock %}
{% block body %}
  {% if messages %}
    <ul class="messages">
      {% for message in messages %}
        <li>{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
    </ul>
  {% endif %}


<form method="post">
  {% csrf_token %}
    <div class="container register-form">
    <div class="form">
      <div class="note">
          <h4 class="my-4">Approve Test Drive</h4>
      </div>
      <div class="form-content">
  {{ form.as_p }}
<!--  <div class="form-check">-->
<!--    <input class="form-check-input" type="checkbox" name="approved" id="approved">-->
<!--    <label class="form-check-label" for="approved">Approved</label>-->
<!--  </div>-->
  <button type="submit" class="btn btn-primary">Submit</button>
          </div>
        </div>
        </div>
</form>
{% endblock %}

web/templates/web/dashboard.html
{% extends 'web/base_alt.html' %}
{% load static %}
{% block title %}Dashboard{% endblock %}
{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/css_style.default.css' %}" id="theme-stylesheet">
{% endblock %}

{% block menu %}
    <ul class="navbar-nav ml-auto">
        <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'web:cars' %}">Cars</a>
        </li>
        {% if user.is_authenticated %}
            {% if user.is_staff %}
           <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="{% url 'web:create_test_drive' %}">Drive Panel</a>
        </li>
       <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="/admin/web/order/">Order Panel</a>
        </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="{% url 'web:dashboard' %}">Welcome, {{ user.last_name }}</a>
            </li>
            {% endif %}
            <li class="nav-item">
                <a class="nav-link js-scroll-t rigger" href="{% url 'web:logout' %}">Logout</a>
            </li>
        {% else %}
            <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="{% url 'web:login' %}">Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="{% url 'web:register' %}">Register</a>
            </li>
        {% endif %}
    </ul>
{% endblock %}

{% block body %}
    <div class="container">
        <!-- /.row -->
    </div>
    <div class="container">

        <!-- Page Heading -->
        <h3 class="my-4">Orders
{#            <small>Secondary Text</small>#}
        </h3>

        <div class="row">
            {% if orders %}
                {% for order in orders %}
                    <div class="col-lg-3 col-md-4 col-sm-6 portfolio-item">
                        <div class="card h-100">
                            <a href="{% url 'web:details' order.car.id %}"><img class="card-img-top" src="{{ order.car.picture.url }}" alt=""></a>
                            <div class="card-body">
                                <h4 class="card-title">
                                    <a href="{% url 'web:details' order.car.id %}">{{ order.car.brand }} {{ order.car.name }}</a>
                                </h4>
                                <p class="card-text">
                                    Amount: &#36; {{ order.amount }}<br>
                                    Date of order: {{ order.order_time }}<br>
                                    Address: {{ order.address }}<br>
                                    Delivered: {% if order.is_delivered %}<i class="fa fa-check"></i>{% else %}<i class="fa fa-times"></i>{% endif %}
                                </p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
        <!-- /.row -->
    </div>
{% endblock %}

web/templates/web/index.html
{% extends 'web/base.html' %}
{% load static %}
{% block title %}DriveZone{% endblock %}
{% block css %}
    <link href="{% static 'css/creative.min.css' %}" rel="stylesheet" type="text/css">
{% endblock %}
{% block menu %}
    <ul class="navbar-nav ml-auto">
        <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#newArrival">Locations</a>
        </li>
        <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#services">Services</a>
        </li>
        <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#cars">Catalogue</a>
        </li>
        <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#contact">Contact</a>
        </li>
        {% if user.is_authenticated %}
            {% if user.is_staff %}
           <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="{% url 'web:create_test_drive' %}">Drive Panel</a>
        </li>
       <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="/admin/web/order/">Order Panel</a>
        </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="{% url 'web:dashboard' %}">Welcome, {{ user.last_name }}</a>
            </li>
            {% endif %}
            <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="{% url 'web:logout' %}">Logout</a>
            </li>
        {% else %}
            <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="{% url 'web:login' %}">Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="{% url 'web:register' %}">Register</a>
            </li>
        {% endif %}
    </ul>
{% endblock %}
{% block body %}
    <header class="masthead text-center text-white d-flex">
        <div class="container my-auto">
            <div class="row">
                <div class="col-lg-10 mx-auto">
                    <h1 class="text-uppercase">
                        <strong>Find your next drive here!</strong>
                    </h1>
                    <hr>
                </div>
                <div class="col-lg-8 mx-auto">
                    <p class="text-faded mb-5">We sell cars. That's it.</p>
                    <a class="btn btn-primary btn-xl js-scroll-trigger" href="{% url 'web:cars' %}">All cars</a>
                </div>
            </div>
        </div>
    </header>

    <section class="bg-primary" id="newArrival">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading">Our showroom locations</h2>
                    <hr class="my-4">
                </div>
                <div class="col-lg-12 mx-auto text-center">
                    <div id="demo" class="carousel slide" data-ride="carousel">
                        <ul class="carousel-indicators">
                            <li data-target="#demo" data-slide-to="0" class="active"></li>
                            <li data-target="#demo" data-slide-to="1"></li>
                            <li data-target="#demo" data-slide-to="2"></li>
                        </ul>
                        <div class="carousel-inner">
                            <div class="carousel-item active">
                                <img src="{% static 'images/los_angeles.jpg' %}" alt="Los Angeles" width="1100" height="500">
                                <div class="carousel-caption">
                                    <h3>Los Angeles</h3>
                                    <p>8152 Sunset Blvd, Los Angeles, CA 90046, USA</p>
                                </div>
                            </div>
                            <div class="carousel-item">
                                <img src="{% static 'images/chicago.jpeg' %}" alt="Chicago" width="1100" height="500">
                                <div class="carousel-caption">
                                    <h3>Chicago</h3>
                                    <p>600 N Clark St, Chicago, IL 60610, USA</p>
                                </div>
                            </div>
                            <div class="carousel-item">
                                <img src="{% static 'images/new_york.jpg' %}" alt="New York" width="1100" height="500">
                                <div class="carousel-caption">
                                    <h3>New York</h3>
                                    <p>160 Broadway, New York, NY 10038, USA</p>
                                </div>
                            </div>
                        </div>
                        <a class="carousel-control-prev" href="#demo" data-slide="prev">
                            <span class="carousel-control-prev-icon"></span>
                        </a>
                        <a class="carousel-control-next" href="#demo" data-slide="next">
                            <span class="carousel-control-next-icon"></span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section id="services">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading">At Your Service</h2>
                    <hr class="my-4">
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="service-box mt-5 mx-auto">
                        <i class="fa fa-4x fa-balance-scale text-primary mb-3 sr-icons"></i>
                        <h3 class="mb-3">Compare cars</h3>
                        <p class="text-muted mb-0">Our website will allow you to compare between cars and let you decide the best car for you.</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="service-box mt-5 mx-auto">
                        <i class="fa fa-4x fa-clock-o text-primary mb-3 sr-icons"></i>
                        <h3 class="mb-3">On time delivery</h3>
                        <p class="text-muted mb-0">Once you order your dream car, we deliver it on the scheduled date. No compromises!</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="service-box mt-5 mx-auto">
                        <i class="fa fa-4x fa-newspaper-o text-primary mb-3 sr-icons"></i>
                        <h3 class="mb-3">Always updated</h3>
                        <p class="text-muted mb-0">We update our stocks and catalogue as new arrivals come in.</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="service-box mt-5 mx-auto">
                        <i class="fa fa-4x fa-life-ring text-primary mb-3 sr-icons"></i>
                        <h3 class="mb-3">Support</h3>
                        <p class="text-muted mb-0">We provide support for your car, even after your car is delivered to you!</p>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="bg-dark text-white" id="cars">
        <div class="container text-center">
            <h2 class="mb-4">Check out all the cars!</h2>
            <a class="btn btn-light btn-xl sr-button" href="{% url 'web:cars' %}">Click here</a>
        </div>
    </section>

    <section id="contact">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto text-center">
                    <h2 class="section-heading">Let's Get In Touch!</h2>
                    <hr class="my-4">
                    <p class="mb-5">Ready to buy the next car from us? That's great! Give us a call or send us an
                        email and we will get back to you as soon as possible!</p>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-4 ml-auto text-center">
                    <i class="fa fa-phone fa-3x mb-3 sr-contact"></i>
                    <p>123-456-6789</p>
                </div>
                <div class="col-lg-4 mr-auto text-center">
                    <i class="fa fa-envelope-o fa-3x mb-3 sr-contact"></i>
                    <p>
                        <a href="mailto:info@drivezone.com">info@drivezone.com</a>
                    </p>
                </div>
            </div>
        </div>
    </section>
{% endblock %}
{% block scripts %}
    <script src="{% static 'js/creative.js' %}"></script>
{% endblock %}

web/templates/web/login.html
{% extends 'web/base_alt.html' %}
{% load static %}
{% block title %}Login{% endblock %}
{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/css_style.default.css' %}" id="theme-stylesheet">
{% endblock %}
{% block menu %}
    <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
            <a class="nav-link js-scroll-trigger active" href="{% url 'web:login' %}">Login</a>
        </li>
        <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'web:register' %}">Register</a>
        </li>
    </ul>
{% endblock %}
{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-6">
                <div class="card" style="margin-top: 1em">
                    <div class="card-body">
                        <h3>Log In</h3>
                        {% if error_message %}
                            <p><strong id="error">{{ error_message }}</strong></p>
                        {% endif %}
                        <form class="form-horizontal" role="form" action="{% url 'web:login'%}" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="id_username">
                                    Username:
                                </label>
                                <div class="col-sm-10">
                                    <input id="id_username" maxlength="30" name="username" type="text">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="id_password">
                                    Password:
                                </label>
                                <div class="col-sm-10">
                                    <input id="id_password" maxlength="30" name="password" type="password">
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button id="submit" type="submit" class="btn btn-success">Login</button>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="card-footer">
                        Don't have an account? <a href="{% url 'web:register' %}">Click here</a> to register!
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

web/templates/web/order_approve.html
{% extends 'web/base_alt.html' %}
{% load widget_tweaks %}
{% load static %}
{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/css_style.default.css' %}" id="theme-stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-datepicker.min.css' %}" id="theme-stylesheet">
{% endblock %}

{% block menu %}

    <ul class="navbar-nav ml-auto">
        <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'web:cars' %}">Cars</a>
        </li>
        {% if user.is_authenticated %}
            {% if user.is_staff %}
           <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="{% url 'web:create_test_drive' %}">Drive Panel</a>
        </li>
       <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="/admin/web/order/">Order Panel</a>
        </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="{% url 'web:dashboard' %}">Welcome, {{ user.last_name }}</a>
            </li>
            {% endif %}
            <li class="nav-item">
                <a class="nav-link js-scroll-t rigger" href="{% url 'web:logout' %}">Logout</a>
            </li>
        {% else %}
            <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="{% url 'web:login' %}">Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="{% url 'web:register' %}">Register</a>
            </li>
        {% endif %}
    </ul>
{% endblock %}
{% block body %}
  {% if messages %}
    <ul class="messages">
      {% for message in messages %}
        <li>{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
    </ul>
  {% endif %}


<form method="post">
  {% csrf_token %}
    <div class="container register-form">
    <div class="form">
      <div class="note">
          <h4 class="my-4">Approve Order</h4>
      </div>
      <div class="form-content">
  {{ form.as_p }}
<!--  <div class="form-check">-->
<!--    <input class="form-check-input" type="checkbox" name="approved" id="approved">-->
<!--    <label class="form-check-label" for="approved">Approved</label>-->
<!--  </div>-->
  <button type="submit" class="btn btn-primary">Submit</button>
          </div>
        </div>
        </div>
</form>
{% endblock %}

web/templates/web/post_car.html
{% extends 'web/base_alt.html' %}
{% load widget_tweaks %}
{% load static %}
{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/css_style.default.css' %}" id="theme-stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-datepicker.min.css' %}" id="theme-stylesheet">
{% endblock %}

{% block menu %}
    <ul class="navbar-nav ml-auto">
        <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'web:cars' %}">Cars</a>
        </li>
        {% if user.is_authenticated %}
            {% if user.is_staff %}
           <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="{% url 'web:create_test_drive' %}">Drive Panel</a>
        </li>
       <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="/admin/web/order/">Order Panel</a>
        </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="{% url 'web:dashboard' %}">Welcome, {{ user.last_name }}</a>
            </li>
            {% endif %}
            <li class="nav-item">
                <a class="nav-link js-scroll-t rigger" href="{% url 'web:logout' %}">Logout</a>
            </li>
        {% else %}
            <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="{% url 'web:login' %}">Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="{% url 'web:register' %}">Register</a>
            </li>
        {% endif %}
    </ul>
{% endblock %}
{% block body %}
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="container register-form">
    <div class="form">
      <div class="note">
          <h4 class="my-4">Post your Car for Sale</h4>
      </div>
      <div class="form-content">
        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              {% render_field form.brand class="form-control" placeholder="Car Brand" %}
            </div>
            <div class="form-group">
              {% render_field form.name class="form-control" placeholder="Car Name" %}
            </div>
            <div class="form-group">
              {% render_field form.car_make class="form-control" placeholder="Car Make" %}
            </div>
            <div class="form-group">
              {% render_field form.price class="form-control" placeholder="Price" %}
            </div>
            {% if user.is_staff %}
            <div class="form-group">
              {% render_field form.commision class="form-control" placeholder="Commission" %}
            </div>
              {% else %}
              <input type="hidden" name="{{ form.commision.name }}" value="0">
              {% endif %}
            <div class="form-group">
              {% render_field form.picture class="form-control" placeholder="Car Picture" %}
            </div>

            <div class="form-group">
              {% render_field form.seats class="form-control" placeholder="Car Seats" %}
            </div>
            <div class="form-group">
              {% render_field form.engine_displacement class="form-control" placeholder="Engine Displacement" %}
            </div>

          </div>
          <div class="col-md-6">
            <div class="form-group">
              {% render_field form.fuel class="form-control" placeholder="Fuel Type" %}
            </div>
            <div class="form-group">
              {% render_field form.dimensions class="form-control" placeholder="Dimensions (mm)" %}
            </div>
            <div class="form-group">
              {% render_field form.transmission class="form-control" placeholder="Transmission Type" %}
            </div>
            <div class="form-group">
              {% render_field form.gears class="form-control" placeholder="Gears" %}
            </div>
              <div class="form-group">
              {% render_field form.power class="form-control" placeholder="Power" %}
            </div>
            <div class="form-group">
              {% render_field form.tank_capacity class="form-control" placeholder="Tank Capacity" %}
            </div>
              <div class="form-group">
              {% render_field form.location class="form-control" placeholder="Location" %}
            </div>
              <input type="hidden" name="{{ form.added_by.name }}" value="{{ request.user.id }}">
          </div>

        </div>
                        <div class="form-group">
              {% render_field form.description class="form-control" placeholder="Description" %}
            </div>
        <button type="submit" class="btnSubmit">Submit</button>
      </div>
    </div>
  </div>

</form>
{% endblock %}
{% block scripts %}
    <script src="{% static 'js/bootstrap-datepicker.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/additional-methods.js' %}" type="text/javascript"></script>

    <script>

        var date = new Date();
        date.setDate(date.getDate()-1);

        $('.datepicker').datepicker({
            format: "dd/mm/yyyy",
            autoclose: true,
            startDate: date
        });

    </script>

{% endblock %}